name: CI for macOS and Windows building with cabal
on:
  push:
    branches:
    - master
    - ci-*
  pull_request:
    branches:
    - master
    - ci-*

jobs:

  cabal:
    name: Cabal
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        ghc:
          - 8.10.7
          - 9.0.2
          - 9.2.4
          - 9.4.2
            # As of 2022-10-06, haskell/actions/setup does not support 9.4.2 yet.
            # Waiting for https://github.com/haskell/actions/pull/115.
      fail-fast: false

    env:
      config: --enable-tests --test-show-details=direct

    steps:

    - name: Setup MSYS path
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "C:\msys64\mingw64\bin;C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Install the ICU library (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-icu

    # Installing ICU is not necessary, macOS-latest already has v69.1
    # - name: Install the ICU library
    #   shell: bash
    #   run: |
    #     brew install icu4c

    - name: Set up pkg-config for the ICU library (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> ${GITHUB_ENV}
        echo "$ ls -l ${PKG_CONFIG_PATH}"
        ls -l ${PKG_CONFIG_PATH}
        echo "$ pkg-config --modversion icu-i18n"
        pkg-config --modversion icu-i18n

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Freeze
      run: |
        cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal configure ${{ env.config }}
        cabal build all

    - name: Test
      run: |
        cabal test all ${{ env.config }}
